// samples/nuxt/quickstart/app/pages/token.vue
<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useThunderID } from '@thunderid/vue'

const dark = useState('dark', () => false)
const { getAccessToken } = useThunderID()

function decodeJwtPart(part) {
  try {
    const base64 = part.replace(/-/g, '+').replace(/_/g, '/')
    const padded = base64.padEnd(base64.length + (4 - (base64.length % 4)) % 4, '=')
    return JSON.parse(atob(padded))
  } catch {
    return null
  }
}

const rawToken = ref(null)
const copied = ref(false)
const now = ref(Math.floor(Date.now() / 1000))
let tickerId = null

const tokenParts = computed(() => rawToken.value ? rawToken.value.split('.') : [])
const jwtHeader = computed(() => tokenParts.value[0] ? decodeJwtPart(tokenParts.value[0]) : null)
const jwtPayload = computed(() => tokenParts.value[1] ? decodeJwtPart(tokenParts.value[1]) : null)

const tokenExp = computed(() => jwtPayload.value?.exp)
const expiresIn = computed(() => tokenExp.value ? tokenExp.value - now.value : null)
const tokenExpired = computed(() => expiresIn.value !== null && expiresIn.value <= 0)
const minsLeft = computed(() => expiresIn.value !== null ? Math.abs(Math.floor(expiresIn.value / 60)) : null)

const issuer = computed(() => jwtPayload.value?.iss)
const audience = computed(() => {
  const aud = jwtPayload.value?.aud
  return Array.isArray(aud) ? aud.join(', ') : aud
})
const scopes = computed(() => jwtPayload.value?.scope)

onMounted(() => {
  getAccessToken().then(t => { rawToken.value = t }).catch(() => {})
  tickerId = setInterval(() => { now.value = Math.floor(Date.now() / 1000) }, 1000)
})

onUnmounted(() => {
  if (tickerId) clearInterval(tickerId)
})

function handleCopy() {
  if (rawToken.value && navigator.clipboard) {
    navigator.clipboard.writeText(rawToken.value)
    copied.value = true
    setTimeout(() => { copied.value = false }, 1500)
  }
}
</script>

<template>
  <div :class="['app', { dark }]">
    <AppNav />
    <div class="home-shell">
      <main class="token-main">
        <div class="token-header">
          <div>
            <h1 class="token-title">Token debug</h1>
            <p class="token-subtitle">Inspect your access token and decoded claims.</p>
          </div>
          <div
            v-if="expiresIn !== null"
            :class="['token-badge', tokenExpired ? 'token-badge--expired' : 'token-badge--valid']"
          >
            <span class="token-badge-dot" />
            <span>{{ tokenExpired ? 'Expired' : `Valid · expires in ${minsLeft} min` }}</span>
          </div>
        </div>

        <div class="token-raw-section">
          <div class="token-raw-label-row">
            <span class="token-section-label">Access token</span>
            <button v-if="rawToken" class="token-copy-btn" @click="handleCopy">
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                <rect x="9" y="9" width="13" height="13" rx="2" />
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
              </svg>
              {{ copied ? 'Copied!' : 'Copy' }}
            </button>
          </div>
          <code v-if="rawToken" class="token-raw">
            <span class="token-part--header">{{ tokenParts[0] }}</span>
            <span class="token-dot">.</span>
            <span class="token-part--payload">{{ tokenParts[1] }}</span>
            <span class="token-dot">.</span>
            <span class="token-part--signature">{{ tokenParts[2] }}</span>
          </code>
          <code v-else class="token-raw token-raw--loading">Loading…</code>
        </div>

        <div class="token-decoded-grid">
          <div class="token-code-box">
            <div class="token-code-box-header token-code-box-header--header">JWT Header</div>
            <pre class="token-code-pre">{{ jwtHeader ? JSON.stringify(jwtHeader, null, 2) : '…' }}</pre>
          </div>
          <div class="token-code-box">
            <div class="token-code-box-header token-code-box-header--payload">JWT Payload</div>
            <pre class="token-code-pre">{{ jwtPayload ? JSON.stringify(jwtPayload, null, 2) : '…' }}</pre>
          </div>
        </div>

        <div v-if="issuer || audience || scopes" class="token-meta-row">
          <div v-if="issuer" class="token-meta-item">
            <div class="token-meta-label">Issuer</div>
            <div class="token-meta-value">{{ issuer }}</div>
          </div>
          <div v-if="audience" class="token-meta-item">
            <div class="token-meta-label">Audience</div>
            <div class="token-meta-value">{{ audience }}</div>
          </div>
          <div v-if="scopes" class="token-meta-item">
            <div class="token-meta-label">Scopes</div>
            <div class="token-meta-value">{{ scopes }}</div>
          </div>
        </div>
      </main>
    </div>
  </div>
</template>

// samples/nextjs/quickstart/app/token/page.tsx
'use client'
import { useState, useEffect } from 'react'
import { fetchAccessToken } from '../actions'
import Nav from '../components/Nav'

function decodeJwtPart(part: string): Record<string, unknown> | null {
  try {
    const base64 = part.replace(/-/g, '+').replace(/_/g, '/')
    const padded = base64.padEnd(base64.length + (4 - (base64.length % 4)) % 4, '=')
    return JSON.parse(atob(padded)) as Record<string, unknown>
  } catch {
    return null
  }
}

function CopyIcon() {
  return (
    <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
      <rect x="9" y="9" width="13" height="13" rx="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  )
}

export default function TokenDebugPage() {
  const [rawToken, setRawToken] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const [now, setNow] = useState(Math.floor(Date.now() / 1000))

  useEffect(() => {
    void fetchAccessToken().then((t) => { if (t) setRawToken(t) })
  }, [])

  useEffect(() => {
    const id = setInterval(() => setNow(Math.floor(Date.now() / 1000)), 1000)
    return () => clearInterval(id)
  }, [])

  const parts = rawToken ? rawToken.split('.') : []
  const jwtHeader = parts[0] ? decodeJwtPart(parts[0]) : null
  const jwtPayload = parts[1] ? decodeJwtPart(parts[1]) : null

  const exp = jwtPayload?.exp as number | undefined
  const expiresIn = exp ? exp - now : null
  const expired = expiresIn !== null && expiresIn <= 0
  const minsLeft = expiresIn !== null ? Math.abs(Math.floor(expiresIn / 60)) : null

  const handleCopy = () => {
    if (rawToken && navigator.clipboard) {
      void navigator.clipboard.writeText(rawToken)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    }
  }

  const issuer = jwtPayload?.iss as string | undefined
  const audience = Array.isArray(jwtPayload?.aud) ? (jwtPayload.aud as string[]).join(', ') : jwtPayload?.aud as string | undefined
  const scopes = jwtPayload?.scope as string | undefined

  return (
    <div className="app">
      <Nav />
      <main className="token-main">
        <div className="token-header">
          <div>
            <h1 className="token-title">Token debug</h1>
            <p className="token-subtitle">Inspect your access token and decoded claims.</p>
          </div>
          {expiresIn !== null && (
            <div className={`token-badge ${expired ? 'token-badge--expired' : 'token-badge--valid'}`}>
              <span className="token-badge-dot" />
              <span>{expired ? 'Expired' : `Valid · expires in ${minsLeft} min`}</span>
            </div>
          )}
        </div>

        {rawToken ? (
          <div className="token-raw-section">
            <div className="token-raw-label-row">
              <span className="token-section-label">Access token</span>
              <button className="token-copy-btn" onClick={handleCopy}>
                <CopyIcon />
                {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
            <code className="token-raw">
              <span className="token-part--header">{parts[0]}</span>
              <span className="token-dot">.</span>
              <span className="token-part--payload">{parts[1]}</span>
              <span className="token-dot">.</span>
              <span className="token-part--signature">{parts[2]}</span>
            </code>
          </div>
        ) : (
          <div className="token-raw-section">
            <div className="token-raw-label-row">
              <span className="token-section-label">Access token</span>
            </div>
            <code className="token-raw token-raw--loading">Loading…</code>
          </div>
        )}

        <div className="token-decoded-grid">
          <div className="token-code-box">
            <div className="token-code-box-header token-code-box-header--header">JWT Header</div>
            <pre className="token-code-pre">
              {jwtHeader ? JSON.stringify(jwtHeader, null, 2) : '…'}
            </pre>
          </div>
          <div className="token-code-box">
            <div className="token-code-box-header token-code-box-header--payload">JWT Payload</div>
            <pre className="token-code-pre">
              {jwtPayload ? JSON.stringify(jwtPayload, null, 2) : '…'}
            </pre>
          </div>
        </div>

        {(issuer ?? audience ?? scopes) && (
          <div className="token-meta-row">
            {issuer && (
              <div className="token-meta-item">
                <div className="token-meta-label">Issuer</div>
                <div className="token-meta-value">{issuer}</div>
              </div>
            )}
            {audience && (
              <div className="token-meta-item">
                <div className="token-meta-label">Audience</div>
                <div className="token-meta-value">{audience}</div>
              </div>
            )}
            {scopes && (
              <div className="token-meta-item">
                <div className="token-meta-label">Scopes</div>
                <div className="token-meta-value">{scopes}</div>
              </div>
            )}
          </div>
        )}
      </main>
    </div>
  )
}
