// packages/nextjs/src/client/components/presentation/SignUp/SignUp.tsx
/**
 * Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

'use client';

import {ThunderIDRuntimeError, EmbeddedFlowType} from '@thunderid/node';
import {BaseSignUp, BaseSignUpProps} from '@thunderid/react';
import {FC} from 'react';
import useThunderID from '../../../contexts/ThunderID/useThunderID';

/**
 * Props for the SignUp component.
 */
export type SignUpProps = BaseSignUpProps;

/**
 * A styled SignUp component that provides embedded sign-up flow with pre-built styling.
 * This component handles the API calls for sign-up and delegates UI logic to BaseSignUp.
 *
 * @example
 * ```tsx
 * import { SignUp } from '@thunderid/react';
 *
 * const App = () => {
 *   return (
 *     <SignUp
 *       onSuccess={(response) => {
 *         console.log('Sign-up successful:', response);
 *         // Handle successful sign-up (e.g., redirect, show confirmation)
 *       }}
 *       onError={(error) => {
 *         console.error('Sign-up failed:', error);
 *       }}
 *       onComplete={(redirectUrl) => {
 *         // Platform-specific redirect handling (e.g., Next.js router.push)
 *         router.push(redirectUrl); // or window.location.href = redirectUrl
 *       }}
 *       size="medium"
 *       variant="outlined"
 *       afterSignUpUrl="/welcome"
 *     />
 *   );
 * };
 * ```
 */
const SignUp: FC<SignUpProps> = ({
  className,
  size = 'medium',
  variant = 'outlined',
  afterSignUpUrl,
  onError,
}: SignUpProps) => {
  const {signUp, applicationId: contextApplicationId, scopes} = useThunderID();

  /**
   * Initialize the sign-up flow.
   */
  const handleInitialize = async (payload?: any): Promise<any> => {
    if (!signUp) {
      throw new ThunderIDRuntimeError(
        '`signUp` function is not available.',
        'SignUp-handleInitialize-RuntimeError-001',
        'nextjs',
      );
    }

    return (await signUp({
      flowType: EmbeddedFlowType.Registration,
      ...(contextApplicationId && {applicationId: contextApplicationId}),
      ...(scopes && {scopes}),
      ...payload,
    })) as unknown as Promise<any>;
  };

  /**
   * Handle sign-up steps.
   */
  const handleOnSubmit = async (payload: any): Promise<any> => {
    if (!signUp) {
      throw new ThunderIDRuntimeError(
        '`signUp` function is not available.',
        'SignUp-handleOnSubmit-RuntimeError-001',
        'nextjs',
      );
    }

    return (await signUp(payload)) as unknown as Promise<any>;
  };

  return (
    <BaseSignUp
      afterSignUpUrl={afterSignUpUrl}
      onInitialize={handleInitialize}
      onSubmit={handleOnSubmit}
      onError={onError}
      className={className}
      size={size}
      variant={variant}
      isInitialized={true}
    />
  );
};

export default SignUp;

// packages/sveltekit/src/components/presentation/SignUp.svelte
<script lang="ts">
  /**
   * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
   *
   * WSO2 LLC. licenses this file to you under the Apache License,
   * Version 2.0 (the "License"); you may not use this file except
   * in compliance with the License.
   * You may obtain a copy of the License at
   *
   *     http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing,
   * software distributed under the License is distributed on an
   * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   * KIND, either express or implied. See the License for the
   * specific language governing permissions and limitations
   * under the License.
   */

  import {useThunderID} from '../../composables/useThunderID';

  interface Props {
    children?: import('svelte').Snippet<[{signUp: () => Promise<void>; loading: boolean}]>;
    signUpOptions?: Record<string, unknown>;
  }

  let {children, signUpOptions = undefined}: Props = $props();

  const tid = useThunderID();

  let loading = $state(false);
  let error = $state<string | null>(null);

  async function handleSignUp(): Promise<void> {
    loading = true;
    error = null;
    try {
      await tid.signUp(signUpOptions);
    } catch (err: unknown) {
      error = (err as any)?.message ?? String(err);
    } finally {
      loading = false;
    }
  }
</script>

{#if children}
  {@render children({signUp: handleSignUp, loading})}
{:else}
  <div class="tid-signup" role="region" aria-label={tid.t('signUp.title')}>
    <h2 class="tid-signup__title">{tid.t('signUp.title')}</h2>
    {#if error}
      <div class="tid-signup__error" role="alert" aria-live="assertive">{tid.t('signUp.error', {error: error ?? ''})}</div>
    {/if}
    <button class="tid-signup__button" disabled={loading} onclick={handleSignUp} aria-busy={loading || undefined}>
      {loading ? tid.t('signUp.loading') : tid.t('signUp.button')}
    </button>
  </div>
{/if}
