// samples/nextjs/quickstart/app/signup/page.tsx
'use client'
import Link from 'next/link'
import { SignedIn, SignedOut, SignUp } from '@thunderid/nextjs'
import Nav from '../components/Nav'

export default function SignUpPage() {
  return (
    <div className="app">
      <Nav />

      <SignedIn>
        <main className="auth-main">
          <div className="auth-card">
            <p className="auth-subtitle">You&apos;re already signed in.</p>
            <Link href="/" className="btn-primary">Go home</Link>
          </div>
        </main>
      </SignedIn>

      <SignedOut>
        <main className="auth-main">
          <SignUp afterSignUpUrl="/" />
        </main>
      </SignedOut>
    </div>
  )
}

// samples/nuxt/quickstart/app/pages/signup.vue
<script setup>
const dark = useState('dark', () => false)
</script>

<template>
  <div :class="['app', { dark }]">
    <AppNav />

    <ThunderIDSignedIn>
      <main class="auth-main">
        <div class="auth-card">
          <p class="auth-subtitle">You're already signed in.</p>
          <NuxtLink to="/" class="btn-primary">Go home</NuxtLink>
        </div>
      </main>
    </ThunderIDSignedIn>

    <ThunderIDSignedOut>
      <main class="auth-main">
        <ThunderIDSignUp after-sign-up-url="/" />
      </main>
    </ThunderIDSignedOut>
  </div>
</template>
